<?php
/**
* @file
* Módulo Node Expiration Date
* Este módulo permite añadir una fecha de caducidad a los nodos.
*/
/**
* Implements hook_help().
*/
function node_expiration_date_help($path, $arg) {
  switch ($path) {
  // Ayuda general para el módulo Node Expiration Date
    case 'admin/help#node_expiration_date':
    return '<p>' . t('This module permits to add an expiration date to any content in the site. The administrator can configure which content types could have an expiration date.') . '</p>';
  }
}

