<?php

/**
* @file
* Modulo de ejemplo
* Este modulo presenta un mensaje de bienvenida al usuaruo de un bloque
*/


/**
* Implements hook_block_info().
*/
function first_example_block_info() {
  //declaracion del bloque
  $blocks['welcome'] = array(
    'info' => t ('My first module: Welcome block'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
* Implements hook_block_view().
*/
function first_example_block_view($delta = '')  {
  //contenido del bloque 'welcome' definido en hook_block_info() .
  $block = array();
  switch ($delta) {
  	case 'welcome';
  	  $block['subject'] = t('myfirst module');
  	  $block['content'] = t('welcome to the drupla site.');
  	break;
  }
  return $block;
}

/**
* Implements hook_help().
*/
function first_example_help($path, $arg) {
  switch ($path) {
  // Ayuda general para el módulo First example
    case 'admin/help#first_example':
  return '<p>' . t('This module shows a welcome message into ablock.') . '</p>';
  // Ayuda particular que se mostrará en el área de administración de bloques
    case 'admin/structure/block':
  return '<p>' . t('Use the block Welcome block to show a welcome message.') . '</p>';
  }
}

